### ISSUE TITLE
Some old GB homebrew of my own

### ISSUE THREAD

**Issue by haroldo-ok** [gb-archive/gb-archive.github.io#1]
I believe your archival project is pretty awesome.
I would like to contribute with some GB homebrew I have made a long time ago: https://github.com/haroldo-ok/really-old-stuff/tree/master/gameboy

**Comment by avivace** [comment]
Thank you! I appreciate that.
I forked the repository and added it to the list of mirrored material.

If you can provide a general "README" with screenshots and a brief description of every homebrew, I'll gladly add you repo to the original [awesome gbdev](https://github.com/avivace/awesome-gbdev) list, too.

**Comment by haroldo-ok** [comment]
Okay, thanks! ;)
I'll see into that.

**Comment by haroldo-ok** [comment]
Okay, I have added a very basic README for the GB entries.

**Comment by avivace** [comment]
Nice job, looks good to me! Thank you, I've added the repository to the list.

**Comment by haroldo-ok** [comment]
Many thanks, and good job on the archiving idea.

**Comment by avivace** [comment]
Glad to have your contributions!
